version: "3"

services:  
  backend:
    build:
      context: backend
      dockerfile: Dockerfile.dev
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ALLOWED_CORS_DOMAINS  : "http://localhost:3000"
      DB_CONNECTION_STRING: "host=db;port=5432;database=blogdb;username=bloguser;password=bloguser"
    depends_on:
      - "db"
    ports:
      - 8080:80
    volumes:
      - ./backend:/src

  db:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - db_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "bloguser"
      POSTGRES_PASSWORD: "bloguser"
      POSTGRES_DB: "blogdb"

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    command: /bin/sh --verbose -c 'yarn install && yarn build && yarn dev'
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
      - frontend-node_modules:/app/node_modules
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_PATH: 'http://localhost:8080/api/v1'

volumes:
  frontend-node_modules:
  db_volume:
